package com.xsx.domain;

public class EmployeeExtension {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeExtension.id
     *
     * @mbggenerated Sat Jan 13 18:19:27 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeExtension.employeeId
     *
     * @mbggenerated Sat Jan 13 18:19:27 CST 2018
     */
    private Integer employeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeExtension.createDate
     *
     * @mbggenerated Sat Jan 13 18:19:27 CST 2018
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeExtension.content
     *
     * @mbggenerated Sat Jan 13 18:19:27 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeExtension.id
     *
     * @return the value of employeeExtension.id
     *
     * @mbggenerated Sat Jan 13 18:19:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeExtension.id
     *
     * @param id the value for employeeExtension.id
     *
     * @mbggenerated Sat Jan 13 18:19:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeExtension.employeeId
     *
     * @return the value of employeeExtension.employeeId
     *
     * @mbggenerated Sat Jan 13 18:19:27 CST 2018
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeExtension.employeeId
     *
     * @param employeeid the value for employeeExtension.employeeId
     *
     * @mbggenerated Sat Jan 13 18:19:27 CST 2018
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeExtension.createDate
     *
     * @return the value of employeeExtension.createDate
     *
     * @mbggenerated Sat Jan 13 18:19:27 CST 2018
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeExtension.createDate
     *
     * @param createdate the value for employeeExtension.createDate
     *
     * @mbggenerated Sat Jan 13 18:19:27 CST 2018
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeExtension.content
     *
     * @return the value of employeeExtension.content
     *
     * @mbggenerated Sat Jan 13 18:19:27 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeExtension.content
     *
     * @param content the value for employeeExtension.content
     *
     * @mbggenerated Sat Jan 13 18:19:27 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}