package com.xsx.domain;

public class Ips {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ips.id
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ips.name
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ips.createDate
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ips.statu
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    private Integer statu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ips.id
     *
     * @return the value of ips.id
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ips.id
     *
     * @param id the value for ips.id
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ips.name
     *
     * @return the value of ips.name
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ips.name
     *
     * @param name the value for ips.name
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ips.createDate
     *
     * @return the value of ips.createDate
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ips.createDate
     *
     * @param createdate the value for ips.createDate
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ips.statu
     *
     * @return the value of ips.statu
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    public Integer getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ips.statu
     *
     * @param statu the value for ips.statu
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    public void setStatu(Integer statu) {
        this.statu = statu;
    }
}