package com.xsx.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.xsx.domain.Ips;
import com.xsx.domain.Page;

public interface IpsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ips
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ips
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    int insert(Ips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ips
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    int insertSelective(Ips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ips
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    Ips selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ips
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    int updateByPrimaryKeySelective(Ips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ips
     *
     * @mbggenerated Sun Dec 03 22:11:46 CST 2017
     */
    int updateByPrimaryKey(Ips record);
    
    /**
     * 获取全部有效的域名
     * @param ips
     * @param page
     * @return
     */
	List<Ips> selectAllOrders(@Param("ips") Ips ips, Page<Ips> page);
	
	/**
	 * 获取全部有效的域名
	 * @return
	 */
	List<Ips> selectAllOrder();
}