package com.xsx.mapper;

import java.util.List;

import com.xsx.domain.WxInfo;

public interface WxInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo
     *
     * @mbggenerated Thu Nov 09 10:38:35 CST 2017
     */
    int deleteAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo
     *
     * @mbggenerated Thu Nov 09 10:38:35 CST 2017
     */
    int insert(WxInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo
     *
     * @mbggenerated Thu Nov 09 10:38:35 CST 2017
     */
    int insertSelective(WxInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo
     *
     * @mbggenerated Thu Nov 09 10:38:35 CST 2017
     */
    WxInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo
     *
     * @mbggenerated Thu Nov 09 10:38:35 CST 2017
     */
    int updateByPrimaryKeySelective(WxInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxinfo
     *
     * @mbggenerated Thu Nov 09 10:38:35 CST 2017
     */
    int updateByPrimaryKey(WxInfo record);
    
    List<WxInfo> selectAll();
}